services:
  Adminfront:
    image: adminfront
    build:
      context: ./Adminfront
      dockerfile: Dockerfile
    ports:
      - "1488:1488"
      - "4173:4173"
  
  Frontendserver:
    image: frontendserver
    build: 
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5252:5252"

  Backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  Frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  
  mongodb:
    image: mongo
    ports:
      - "6969:27017"
    environment:
      MONGODB_HOSTNAME: mongodb
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_DATABASE: admin
      COMMON_DATABASE: commonDB
      COMMON_USERNAME: common
      COMMON_PASSWORD: password
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example